"use client";

import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "es" | "fr" | "rw" | "sw";
const LANGUAGE_KEY = "app_language"

const dict: Record<Language, Record<string, string>> = {
  en: {
    loading: "Loading",
    parentZoneTitleSuffix: "'s Dashboard",
    child: "Child",
    subtitleAgeRange: "For parents of curious 2-4 year olds",
    addChild: "Add Child",
    addNewChild: "Add New Child",
    childName: "Child's Name",
    childNamePlaceholder: "Enter child's name",
    saving: "Saving...",
    save: "Save",
    cancel: "Cancel",
    saved: "Saved",
    addChildError:"Error adding child",
    profileSaved: "Your profile has been updated",
    editProfile: "Edit Profile",
    ageRange: "Age Range",
    selectAge: "Select age range",
    avatarUrl: "Avatar URL",
    favoriteTheme: "Favorite Theme",
    selectTheme: "Select a theme",
    themeOcean: "Ocean",
    freePlanLimitReached: "You've reached the limit of {max} children on the free plan",
    themeSpace: "Space",
    themeSafari: "Safari",
    profileTip: "Tip: Keep profile updated to receive more personalized activities.",
    weeklyAdventures: "This Week's Adventures (Weekly Report)",
    thisWeek: "This week",
    upgradeRequired:"Upgrade to premium to add more children",
    day: "Day",
    done: "done",
    missed: "missed",
    activitiesCompleted: "of activities completed!",
    weeklyBadge: "Weekly Badge",
    weeklyBadgeDesc: "Earned for consistent learning across the week.",
    settings: "Settings",
    screenTime: "Screen Time",
    min: "min",
    screenTimeHint: "Set a balanced daily screen time. You can adjust anytime.",
    bedtimeMode: "Bedtime Mode",
    bedtimeHint: "Bedtime mode dims colors for a calmer evening experience.",
    kidSafeOnly: "Kid-Safe Only",
    kidSafeHint: "Blocks external links. Use whitelist to allow specific sites.",
    whitelistTitle: "Allowed sites (hostname only)",
    addDomain: "Add",
    remove: "Remove",
    domainPlaceholder: "e.g. example.com",
    whitelistNote: "By default, only in-app content is allowed.",
    blockedExternal: "External links are blocked by Kid-Safe mode.",
    footerTagline: "Designed with ❤️ for early learning journeys",
    // Premium
    premiumBenefits: "Premium Benefits",
    manageSubscription: "Manage Subscription",
    premiumPitch: "Parents trust Nimi for peace of mind and deeper insight into progress.",
    premiumBullet1: "100+ expertly crafted games and stories",
    premiumBullet2: "Weekly skill insights tailored to your child",
    premiumBullet3: "Advanced screen-time and bedtime controls",
    premiumBullet4: "Kid-safe, ad-free environment",
    premiumBullet5: "Exclusive Nimi Glory stickers and rewards",
    premiumGuarantee: "14‑day free trial. Cancel anytime. Secure payments and private by design.",
    premiumDeliveriesTitle: "Weekly Deliveries (Subscribers)",
    weeklyHardStorybook: "Hardcover storybook",
    weeklyColoringBook: "Coloring book (colorage)",
    chooseDeliveryDay: "Choose delivery day",
    subscribeToUnlockDeliveries: "Subscribe to unlock weekly book deliveries.",
    savePreferences: "Save preferences",
    // Subscription copy
    premiumTitle: "Premium",
    premiumHeadline: "Unlock a calmer, smarter learning journey",
    premiumSubhead: "Evidence‑based controls and playful content for ages 2–4.",
    planMonthly: "Monthly",
    planYearly: "Yearly",
    bestValue: "Best Value",
    perMonth: "per month",
    perYear: "per year",
    f1: "Unlimited premium games and stories",
    f2: "Weekly progress insights and skill trends",
    f3: "Advanced screen time tools",
    f4: "Ad‑free, safe experience",
    f5: "Exclusive Nimi Glory stickers",
    startTrial: "Start Free Trial",
    trialNote: "Cancel anytime. Trial converts to paid at end of period.",
    benefit1Title: "Motivating",
    benefit1Desc: "Rewards like Nimi Glory stickers encourage healthy habits.",
    benefit2Title: "Personalized",
    benefit2Desc: "Activities adapt to your child's interests and pace.",
    benefit3Title: "Protected",
    benefit3Desc: "Best‑in‑class controls and content safety.",
    backToParentZone: "Back to Parent Zone",
    // Sticker
    downloadSticker: "Download Nimi Glory Sticker",
    stickerPreviewTitle: "Nimi Glory Sticker of the Week",
    stickerPreviewAlt: "Nimi Glory sticker preview",
    // Parent profile / auth / notifications
    parentProfileTitle: "Parent Profile",
    parentName: "Your Name",
    parentEmail: "Email",
    notifyEmail: "Weekly email reports",
    notifyEmailHint: "Receive a weekly progress summary.",
    marketingOptIn: "Product tips & updates",
    marketingOptInHint: "Occasional emails to help you get the most from Nimi.",
    authStatus: "Status",
    authLogin: "Log in",
    authLogout: "Log out",
    loggedIn: "Logged in",
    loggedOut: "Logged out",
    loginError: "Login failed",
    enterEmail: "Please enter your email",
    subscriptionStatus: "Subscription",
    subscribed: "Subscribed",
    notSubscribed: "Not subscribed",
    remindersTitle: "Daily learning reminders",
    addReminder: "Add time",
    grantPermission: "Allow notifications",
    remindersHint: "We’ll remind your child at the selected times to come learn with Nimi.",
    notificationsEnabled: "Notifications enabled",
    notificationsDenied: "Notifications blocked",
    learnReminderBody: "Time to learn with Nimi! A quick play can make a big difference.",
    Child: "Child",
    noChildrenTitle: "No children added yet",
    noChildrenDescription: "Add a child to get started with personalized learning",
    addFirstChild: "Add your first child",
    upgradeNow: "Upgrade Now",
    unlockPremiumFeatures: "Unlock Premium Features",
    premiumUpsellDescription: "Access premium features with a subscription",
    offlineActivities: "Offline Activities",
    offlineActivitiesDesc: "Enjoy activities without internet connection",
    coloringBook: "Coloring Book",
    coloringBookDesc: "A fun book for coloring",
    download: "Download",
    storyBook: "Story Book",
    storyBookDesc: "Read stories anytime",
    activityPack: "Activity Pack",
    activityPackDesc: "Extra activities to enjoy",
    upgradeToDownload: "Upgrade to Download",
    familyAccountLinking: "Family Account Linking",
    familyAccountLinkingDesc: "Connect multiple family accounts",
    premiumFeature: "Premium Feature",
    familyLinkingPremiumDesc: "Family linking available in premium plan",
    overview: "Overview",
    progress: "Progress",
    safety: "Safety",
    premium: "Premium",
    weeklyReport: "Weekly Report (Adventures)",
    noActivitiesYet: "No activities yet",
    achievements: "Achievements",
    firstActivity: "First Activity",
    completedFirstActivity: "Completed first activity",
    weekStreak: "Week Streak",
    sevenDaysInARow: "7 days in a row",
    explorer: "Explorer",
    triedFiveActivities: "Tried 5 different activities",
    timeMaster: "Time Master",
    completedAllWeeklyActivities: "Completed all weekly activities",
    viewAllAchievements: "View All Achievements",
    engagement: "Engagement",
    activityReminders: "Activity Reminders",
    voiceAssistant: "Voice Assistant",
    parentingTips: "Parenting Tips",
    sampleTip: "Sample Tip",
    readMore: "Read More",
    screenTimeTrends: "Screen Time Trends",
    activityCompletion: "Activity Completion",
    completedPending: "Completed / Pending",
    comparisonView: "Comparison View",
    compareProgress: "Compare Progress",
    bedtimeScheduler: "Bedtime Scheduler",
    bedtimeSchedulerDescription: "Set the time for bedtime",
    startTime: "Start Time",
    endTime: "End Time",
    bedtimeActive: "Bedtime Active",
    bedtimeActiveDescription: "21:00 - 07:00",
    premiumUpsell: "Unlock premium features with subscription",
    noSubscriptionTitle: "No Subscription Yet",
    noSubscriptionDesc: "Subscribe now to access all features",
    unlockFeatures: "Unlock Features",
    
  },
  sw: {
    loading: "Inapakia",
    parentZoneTitleSuffix: " Eneo la Mzazi",
    child: "Mtoto",
    addChildError:"Hitilafu ya kuongeza mtoto",
    subtitleAgeRange: "Kwa wazazi wa watoto wenye hamu ya kujifunza (miaka 2–4)",
    addChild: "Ongeza Mtoto",
    addNewChild: "Ongeza Mtoto Mpya",
    childName: "Jina la Mtoto",
    childNamePlaceholder: "Weka jina la mtoto",
    saving: "Inahifadhi...",
    save: "Hifadhi",
    cancel: "Ghairi",
    saved: "Imehifadhiwa",
    profileSaved: "Profaili yako imesasishwa",
    editProfile: "Hariri Wasifu",
    ageRange: "Umri",
    selectAge: "Chagua umri",
    avatarUrl: "Picha ya Profaili (URL)",
    favoriteTheme: "Mandhari Uipendayo",
    selectTheme: "Chagua mandhari",
    themeOcean: "Bahari",
    themeSpace: "Anga",
    themeSafari: "Safari",
    profileTip: "Ushauri: Sasisha profaili ili kupata shughuli zilizo bunifu zaidi.",
    weeklyAdventures: "Ripoti ya Wiki Hii (Shughuli)",
    thisWeek: "Wiki hii",
    day: "Siku",
    done: "imekamilika",
    missed: "imekosa",
    activitiesCompleted: "ya shughuli zimekamilika!",
    settings: "Mipangilio",
    screenTime: "Muda wa Skrini",
    min: "dak",
    upgradeRequired: "Pata premium kuongeza watoto zaidi",
    freePlanLimitReached: "Umefikia kikomo cha {max} watoto kwenye mpango wa bure",
    screenTimeHint: "Weka muda bora wa kila siku wa skrini. Unaweza kubadilisha wakati wowote.",
    bedtimeMode: "Hali ya Kulala",
    bedtimeHint: "Hali ya kulala hupunguza rangi kwa utulivu wa jioni.",
    kidSafeOnly: "Usalama kwa Watoto Tu",
    kidSafeHint: "Huzuia viungo vya nje. Tumia orodha nyeupe kuruhusu tovuti fulani.",
    whitelistTitle: "Tovuti zinazoruhusiwa (jina la kikoa)",
    addDomain: "Ongeza",
    remove: "Ondoa",
    domainPlaceholder: "mf. mfano.com",
    whitelistNote: "Kwa chaguo-msingi, maudhui ya ndani tu yanaruhusiwa.",
    blockedExternal: "Viungo vya nje vimezuiwa na hali ya usalama kwa watoto.",
    footerTagline: "Imetengenezwa kwa ❤️ kwa safari za ujifunzaji za mapema",
    premiumBenefits: "Faida za Premium",
    manageSubscription: "Dhibiti Usajili",
    premiumPitch: "Wazazi huamini Nimi kwa utulivu na uelewa wa maendeleo.",
    premiumBullet1: "Michezo na hadithi 100+ zilizoundwa na wataalam",
    premiumBullet2: "Mtazamo wa ujuzi wa kila wiki unaolingana na mtoto wako",
    premiumBullet3: "Udhibiti wa hali ya juu wa muda wa skrini na kulala",
    premiumBullet4: "Mazingira salama bila matangazo",
    premiumBullet5: "Stika na tuzo za Nimi Glory za kipekee",
    premiumGuarantee: "Jaribio la siku 14 bure. Malipo salama, faragha mbele.",
    premiumDeliveriesTitle: "Usafirishaji wa Kila Wiki (Waliosajiliwa)",
    weeklyHardStorybook: "Kitabu cha hadithi kigumu",
    weeklyColoringBook: "Kitabu cha kuchorea",
    chooseDeliveryDay: "Chagua siku ya usafirishaji",
    subscribeToUnlockDeliveries: "Jisajili kufungua vitabu vya kila wiki.",
    savePreferences: "Hifadhi mapendeleo",
    premiumTitle: "Premium",
    premiumHeadline: "Fungua safari tulivu na yenye akili ya ujifunzaji",
    premiumSubhead: "Zana zinazothibitishwa na maudhui ya kufurahisha kwa miaka 2–4.",
    planMonthly: "Kwa Kila Mwezi",
    planYearly: "Kwa Kila Mwaka",
    bestValue: "Thamani Bora",
    perMonth: "kwa mwezi",
    perYear: "kwa mwaka",
    f1: "Michezo na hadithi za premium zisizo na kikomo",
    f2: "Mtazamo wa maendeleo ya kila wiki",
    f3: "Vifaa vya hali ya juu vya muda wa skrini",
    f4: "Bila matangazo, salama",
    f5: "Stika za Nimi Glory za kipekee",
    startTrial: "Anza Jaribio Bure",
    trialNote: "Ghairi wakati wowote. Jaribio hubadilika kuwa malipo mwishoni.",
    benefit1Title: "Huchochea",
    benefit1Desc: "Zawadi kama stika za Nimi Glory huchochea tabia njema.",
    benefit2Title: "Iliyobinafsishwa",
    benefit2Desc: "Shughuli huendana na maslahi na mwendo wa mtoto wako.",
    benefit3Title: "Imelindwa",
    benefit3Desc: "Udhibiti na usalama wa maudhui wa kiwango cha juu.",
    backToParentZone: "Rudi Eneo la Mzazi",
    downloadSticker: "Pakua Stika ya Nimi Glory",
    stickerPreviewTitle: "Stika ya Nimi Glory ya Wiki",
    stickerPreviewAlt: "Hakikisho la stika ya Nimi Glory",
    parentProfileTitle: "Profaili ya Mzazi",
    parentName: "Jina Lako",
    parentEmail: "Barua pepe",
    notifyEmail: "Ripoti za barua pepe za kila wiki",
    notifyEmailHint: "Pokea muhtasari wa maendeleo kila wiki.",
    marketingOptIn: "Vidokezo & masasisho ya bidhaa",
    marketingOptInHint: "Barua pepe chache kukusaidia kutumia Nimi vyema.",
    authStatus: "Hali",
    authLogin: "Ingia",
    authLogout: "Toka",
    loggedIn: "Umeingia",
    loggedOut: "Hujaingia",
    loginError: "Kuingia kumeshindikana",
    enterEmail: "Tafadhali weka barua pepe yako",
    subscriptionStatus: "Usajili",
    subscribed: "Umesajiliwa",
    notSubscribed: "Huja sajiliwa",
    remindersTitle: "Vikumbusho vya kila siku vya kujifunza",
    addReminder: "Ongeza muda",
    grantPermission: "Ruhusu arifa",
    remindersHint: "Tutamkumbusha mtoto wako kwa nyakati ulizochagua.",
    notificationsEnabled: "Arifa zimewezeshwa",
    notificationsDenied: "Arifa zimekataliwa",
    learnReminderBody: "Ni wakati wa kujifunza na Nimi! Mchezo mfupi unaweza kusaidia sana.",
    upgradeNow: "Boresha Sasa",
    unlockPremiumFeatures: "Fungua Vipengele vya Premium",
    premiumUpsellDescription: "Pata vipengele vya premium kwa usajili",
    offlineActivities: "Shughuli Bila Mtandao",
    offlineActivitiesDesc: "Furahia shughuli bila muunganisho wa intaneti",
    coloringBook: "Kitabu cha Rangi",
    coloringBookDesc: "Kitabu cha kufurahisha cha rangi",
    download: "Pakua",
    storyBook: "Kitabu cha Hadithi",
    storyBookDesc: "Soma hadithi wakati wowote",
    activityPack: "Kifurushi cha Shughuli",
    activityPackDesc: "Shughuli za ziada za kufurahia",
    upgradeToDownload: "Boresha Ili Kupakua",
    familyAccountLinking: "Kuunganisha Akaunti za Familia",
    familyAccountLinkingDesc: "Unganisha akaunti nyingi za familia",
    premiumFeature: "Kipengele cha Premium",
    familyLinkingPremiumDesc: "Uunganishaji wa familia upo katika mpango wa premium",
    overview: "Muhtasari",
    progress: "Maendeleo",
    safety: "Usalama",
    premium: "Premium",
    weeklyReport: "Ripoti ya Wiki (Michezo)",
    noActivitiesYet: "Hakuna shughuli bado",
    achievements: "Mafanikio",
    firstActivity: "Shughuli ya Kwanza",
    completedFirstActivity: "Umeisha Shughuli ya Kwanza",
    weekStreak: "Mfuatano wa Wiki",
    sevenDaysInARow: "Siku 7 mfululizo",
    explorer: "Mchunguzi",
    triedFiveActivities: "Umejaribu shughuli 5 tofauti",
    timeMaster: "Mkuu wa Muda",
    completedAllWeeklyActivities: "Umeisha shughuli zote za wiki",
    viewAllAchievements: "Angalia Mafanikio Yote",
    engagement: "Ushiriki",
    activityReminders: "Kikumbusho cha Shughuli",
    voiceAssistant: "Msaidizi wa Sauti",
    parentingTips: "Vidokezo vya Ulezi",
    sampleTip: "Kipengele cha Mfano",
    readMore: "Soma Zaidi",
    screenTimeTrends: "Mwelekeo wa Muda wa Skrini",
    activityCompletion: "Ukomo wa Shughuli",
    completedPending: "Imekamilika / Inasubiri",
    comparisonView: "Mtazamo wa Kulinganisha",
    compareProgress: "Linganisho la Maendeleo",
    bedtimeScheduler: "Ratiba ya Kulala",
    bedtimeSchedulerDescription: "Weka muda wa kulala",
    startTime: "Muda wa Kuanzia",
    endTime: "Muda wa Kuisha",
    bedtimeActive: "Kulala Kumeanzishwa",
    bedtimeActiveDescription: "21:00 - 07:00"
  },
  fr: {
    loading: "Chargement",
    parentZoneTitleSuffix: " - Espace Parent",
    child: "Enfant",
    subtitleAgeRange: "Pour les parents d'explorateurs de 2 à 4 ans",
    addChild: "Ajouter un Enfant",
    addNewChild: "Ajouter un Nouvel Enfant",
    childName: "Nom de l'Enfant",
    childNamePlaceholder: "Entrez le nom de l'enfant",
    saving: "Enregistrement...",
    save: "Enregistrer",
    cancel: "Annuler",
    saved: "Enregistré",
    upgradeRequired:"Passez à premium pour ajouter plus d'enfants",
    addChildError:"Erreur lors de l'ajout d'un enfant",
    freePlanLimitReached:"Vous avez atteint la limite de {max} enfants sur le plan gratuit",
    profileSaved: "Votre profil a été mis à jour",
    editProfile: "Modifier le Profil",
    ageRange: "Tranche d'âge",
    selectAge: "Sélectionnez l'âge",
    avatarUrl: "URL de l'Avatar",
    favoriteTheme: "Thème Préféré",
    selectTheme: "Choisissez un thème",
    themeOcean: "Océan",
    themeSpace: "Espace",
    themeSafari: "Safari",
    profileTip: "Astuce : Mettez à jour le profil pour des activités plus personnalisées.",
    weeklyAdventures: "Rapport Hebdomadaire (Aventures)",
    thisWeek: "Cette semaine",
    day: "Jour",
    done: "fait",
    missed: "manqué",
    activitiesCompleted: "des activités terminées !",
    settings: "Paramètres",
    screenTime: "Temps d'écran",
    min: "min",
    screenTimeHint: "Définissez un temps d'écran quotidien équilibré. Ajustable à tout moment.",
    bedtimeMode: "Mode Coucher",
    bedtimeHint: "Assombrit les couleurs pour une soirée plus calme.",
    kidSafeOnly: "Mode Enfant",
    kidSafeHint: "Bloque les liens externes. Utilisez la liste blanche pour autoriser des sites.",
    whitelistTitle: "Sites autorisés (nom d'hôte)",
    addDomain: "Ajouter",
    remove: "Supprimer",
    domainPlaceholder: "ex. exemple.com",
    whitelistNote: "Par défaut, seul le contenu de l'application est autorisé.",
    blockedExternal: "Les liens externes sont bloqués par le Mode Enfant.",
    footerTagline: "Conçu avec ❤️ pour les premiers apprentissages",
    premiumBenefits: "Avantages Premium",
    manageSubscription: "Gérer l'Abonnement",
    premiumPitch: "Les parents font confiance à Nimi pour la sérénité et une meilleure visibilité des progrès.",
    premiumBullet1: "100+ jeux et histoires conçus par des experts",
    premiumBullet2: "Analyses hebdomadaires adaptées à votre enfant",
    premiumBullet3: "Contrôles avancés du temps d'écran et du coucher",
    premiumBullet4: "Environnement sûr et sans publicité",
    premiumBullet5: "Autocollants et récompenses Nimi Glory exclusifs",
    premiumGuarantee: "Essai gratuit de 14 jours. Annulation à tout moment. Paiements sécurisés.",
    premiumDeliveriesTitle: "Livraisons hebdomadaires (Abonnés)",
    weeklyHardStorybook: "Livre d'histoires relié",
    weeklyColoringBook: "Livre de coloriage",
    chooseDeliveryDay: "Choisir le jour de livraison",
    subscribeToUnlockDeliveries: "Abonnez-vous pour débloquer les livres hebdomadaires.",
    savePreferences: "Enregistrer les préférences",
    premiumTitle: "Premium",
    premiumHeadline: "Débloquez un parcours d'apprentissage plus serein et intelligent",
    premiumSubhead: "Des outils fondés sur des preuves et des contenus ludiques pour 2–4 ans.",
    planMonthly: "Mensuel",
    planYearly: "Annuel",
    bestValue: "Meilleure Offre",
    perMonth: "par mois",
    perYear: "par an",
    f1: "Jeux et histoires premium illimités",
    f2: "Aperçus hebdomadaires des progrès et des compétences",
    f3: "Outils avancés de temps d'écran",
    f4: "Expérience sécurisée sans publicité",
    f5: "Autocollants Nimi Glory exclusifs",
    startTrial: "Commencer l'essai gratuit",
    trialNote: "Annulation à tout moment. L'essai devient payant en fin de période.",
    benefit1Title: "Motivant",
    benefit1Desc: "Des récompenses comme les autocollants Nimi Glory encouragent de bonnes habitudes.",
    benefit2Title: "Personnalisé",
    benefit2Desc: "Les activités s'adaptent aux intérêts et au rythme de votre enfant.",
    benefit3Title: "Protégé",
    benefit3Desc: "Des contrôles et une sécurité de contenu de premier ordre.",
    backToParentZone: "Retour à l'Espace Parent",
    downloadSticker: "Télécharger l'autocollant Nimi Glory",
    stickerPreviewTitle: "Autocollant Nimi Glory de la Semaine",
    stickerPreviewAlt: "Aperçu de l'autocollant Nimi Glory",
    parentProfileTitle: "Profil du Parent",
    parentName: "Votre nom",
    parentEmail: "Email",
    notifyEmail: "Rapports hebdomadaires par email",
    notifyEmailHint: "Recevez un résumé hebdomadaire des progrès.",
    marketingOptIn: "Astuces & mises à jour produit",
    marketingOptInHint: "Quelques emails pour profiter au mieux de Nimi.",
    authStatus: "Statut",
    authLogin: "Se connecter",
    authLogout: "Se déconnecter",
    loggedIn: "Connecté",
    loggedOut: "Non connecté",
    loginError: "Échec de connexion",
    enterEmail: "Veuillez entrer votre email",
    subscriptionStatus: "Abonnement",
    subscribed: "Abonné",
    notSubscribed: "Non abonné",
    remindersTitle: "Rappels quotidiens d'apprentissage",
    addReminder: "Ajouter une heure",
    grantPermission: "Autoriser les notifications",
    remindersHint: "Nous rappellerons à votre enfant aux heures choisies.",
    notificationsEnabled: "Notifications activées",
    notificationsDenied: "Notifications bloquées",
    learnReminderBody: "C'est l'heure d'apprendre avec Nimi ! Quelques minutes font la différence.",
    upgradeNow: "Mettre à Niveau Maintenant",
    unlockPremiumFeatures: "Déverrouiller les Fonctions Premium",
    premiumUpsellDescription: "Accédez aux fonctionnalités premium avec un abonnement",
    offlineActivities: "Activités Hors Ligne",
    offlineActivitiesDesc: "Profitez des activités sans connexion Internet",
    coloringBook: "Livre de Coloriage",
    coloringBookDesc: "Un livre amusant pour colorier",
    download: "Télécharger",
    storyBook: "Livre d’Histoires",
    storyBookDesc: "Lire des histoires à tout moment",
    activityPack: "Pack d’Activités",
    activityPackDesc: "Activités supplémentaires à apprécier",
    upgradeToDownload: "Mettre à Niveau pour Télécharger",
    familyAccountLinking: "Liaison de Comptes Familiaux",
    familyAccountLinkingDesc: "Connectez plusieurs comptes familiaux",
    premiumFeature: "Fonctionnalité Premium",
    familyLinkingPremiumDesc: "La liaison familiale est disponible dans le plan premium",
    overview: "Aperçu",
    progress: "Progrès",
    safety: "Sécurité",
    premium: "Premium",
    weeklyReport: "Rapport Hebdomadaire (Aventures)",
    noActivitiesYet: "Aucune activité pour le moment",
    achievements: "Réalisations",
    firstActivity: "Première Activité",
    completedFirstActivity: "Première activité complétée",
    weekStreak: "Série de la semaine",
    sevenDaysInARow: "7 jours consécutifs",
    explorer: "Explorateur",
    triedFiveActivities: "A essayé 5 activités différentes",
    timeMaster: "Maître du Temps",
    completedAllWeeklyActivities: "Toutes les activités hebdomadaires terminées",
    viewAllAchievements: "Voir Toutes les Réalisations",
    engagement: "Engagement",
    activityReminders: "Rappels d'Activité",
    voiceAssistant: "Assistant Vocal",
    parentingTips: "Conseils Parentaux",
    sampleTip: "Exemple de Conseil",
    readMore: "Lire Plus",
    screenTimeTrends: "Tendances du Temps d'Écran",
    activityCompletion: "Achèvement des Activités",
    completedPending: "Complété / En Attente",
    comparisonView: "Vue de Comparaison",
    compareProgress: "Comparer le Progrès",
    bedtimeScheduler: "Planificateur de Coucher",
    bedtimeSchedulerDescription: "Définir l'heure du coucher",
    startTime: "Heure de Début",
    endTime: "Heure de Fin",
    bedtimeActive: "Coucher Actif",
    bedtimeActiveDescription: "21:00 - 07:00",
    premiumUpsell: "Déverrouillez les fonctionnalités premium avec un abonnement",
    noSubscriptionTitle: "Pas encore d'abonnement",
    noSubscriptionDesc: "Abonnez-vous maintenant pour accéder à toutes les fonctionnalités",
    unlockFeatures: "Déverrouiller les fonctionnalités"



  },
  es: {
    loading: "Cargando",
    parentZoneTitleSuffix: " - Zona para Padres",
    child: "Niño",
    subtitleAgeRange: "Para familias de pequeños curiosos de 2 a 4 años",
    addChild: "Añadir Niño",
    addNewChild: "Añadir Nuevo Niño",
    childName: "Nombre del Niño",
    childNamePlaceholder: "Ingrese el nombre del niño",
    saving: "Guardando...",
    save: "Guardar",
    cancel: "Cancelar",
    saved: "Guardado",
    profileSaved: "Tu perfil ha sido actualizado",
    editProfile: "Editar Perfil",
    ageRange: "Rango de edad",
    selectAge: "Seleccione la edad",
    avatarUrl: "URL del Avatar",
    favoriteTheme: "Tema Favorito",
    selectTheme: "Seleccione un tema",
    themeOcean: "Océano",
    themeSpace: "Espacio",
    themeSafari: "Safari",
    profileTip: "Consejo: Mantenga el perfil actualizado para actividades más personalizadas.",
    weeklyAdventures: "Informe Semanal (Aventuras)",
    thisWeek: "Esta semana",
    day: "Día",
    done: "hecho",
    missed: "faltó",
    activitiesCompleted: "de actividades completadas",
    settings: "Configuración",
    screenTime: "Tiempo de pantalla",
    min: "min",
    screenTimeHint: "Defina un tiempo de pantalla equilibrado. Ajustable en cualquier momento.",
    bedtimeMode: "Modo Dormir",
    bedtimeHint: "Atenúa los colores para una tarde más tranquila.",
    kidSafeOnly: "Solo contenido infantil",
    kidSafeHint: "Bloquea enlaces externos. Use la lista blanca para permitir sitios.",
    whitelistTitle: "Sitios permitidos (dominio)",
    addDomain: "Añadir",
    remove: "Quitar",
    freePlanLimitReached:"Has alcanzado el límite de {max} niños en el plan gratuito",
    upgradeRequired:"Actualiza a premium para añadir más niños",
    domainPlaceholder: "p. ej. ejemplo.com",
    whitelistNote: "Por defecto, solo el contenido de la app está permitido.",
    blockedExternal: "Los enlaces externos están bloqueados por el modo infantil.",
    footerTagline: "Diseñado con ❤️ para los primeros aprendizajes",
    premiumBenefits: "Beneficios Premium",
    manageSubscription: "Gestionar Suscripción",
    premiumPitch: "Los padres confían en Nimi por tranquilidad y visión del progreso.",
    premiumBullet1: "Más de 100 juegos e historias creados por expertos",
    premiumBullet2: "Ideas semanales adaptadas a tu hijo",
    premiumBullet3: "Controles avanzados de pantalla y hora de dormir",
    premiumBullet4: "Entorno seguro y sin anuncios",
    premiumBullet5: "Pegatinas y recompensas Nimi Glory exclusivas",
    premiumGuarantee: "Prueba de 14 días gratis. Pagos seguros y privados.",
    premiumDeliveriesTitle: "Entregas semanales (Suscriptores)",
    weeklyHardStorybook: "Libro de cuentos de tapa dura",
    weeklyColoringBook: "Libro de colorear",
    chooseDeliveryDay: "Elige el día de entrega",
    subscribeToUnlockDeliveries: "Suscríbete para desbloquear los libros semanales.",
    savePreferences: "Guardar preferencias",
    premiumTitle: "Premium",
    premiumHeadline: "Desbloquea un aprendizaje más tranquilo e inteligente",
    premiumSubhead: "Controles basados en evidencia y contenido lúdico para 2–4 años.",
    planMonthly: "Mensual",
    planYearly: "Anual",
    bestValue: "Mejor Oferta",
    perMonth: "por mes",
    perYear: "por año",
    f1: "Juegos e historias premium ilimitados",
    f2: "Ideas semanales sobre progreso y habilidades",
    f3: "Herramientas avanzadas de tiempo de pantalla",
    f4: "Experiencia segura y sin anuncios",
    f5: "Pegatinas Nimi Glory exclusivas",
    startTrial: "Comenzar prueba gratis",
    trialNote: "Cancela cuando quieras. La prueba pasa a pago al finalizar.",
    benefit1Title: "Motivador",
    benefit1Desc: "Las pegatinas Nimi Glory refuerzan hábitos saludables.",
    benefit2Title: "Personalizado",
    benefit2Desc: "Actividades que se adaptan a intereses y ritmo.",
    benefit3Title: "Protegido",
    benefit3Desc: "Controles y seguridad de primer nivel.",
    backToParentZone: "Volver a Zona para Padres",
    downloadSticker: "Descargar pegatina Nimi Glory",
    stickerPreviewTitle: "Pegatina Nimi Glory de la Semana",
    stickerPreviewAlt: "Vista previa de pegatina Nimi Glory",
    parentProfileTitle: "Perfil del Padre/Madre",
    parentName: "Tu nombre",
    parentEmail: "Correo electrónico",
    notifyEmail: "Informes semanales por correo",
    notifyEmailHint: "Recibe un resumen semanal del progreso.",
    marketingOptIn: "Consejos y actualizaciones",
    marketingOptInHint: "Correos ocasionales para aprovechar al máximo Nimi.",
    authStatus: "Estado",
    authLogin: "Iniciar sesión",
    authLogout: "Cerrar sesión",
    loggedIn: "Sesión iniciada",
    loggedOut: "Sin iniciar sesión",
    loginError: "Error de inicio de sesión",
    enterEmail: "Introduce tu correo",
    subscriptionStatus: "Suscripción",
    addChildError:"Error al añadir niño",
    subscribed: "Suscrito",
    notSubscribed: "No suscrito",
    remindersTitle: "Recordatorios diarios de aprendizaje",
    addReminder: "Agregar hora",
    grantPermission: "Permitir notificaciones",
    remindersHint: "Recordaremos a tu hijo a las horas elegidas.",
    notificationsEnabled: "Notificaciones habilitadas",
    notificationsDenied: "Notificaciones bloqueadas",
    learnReminderBody: "¡Es hora de aprender con Nimi! Un ratito marca la diferencia.",
    upgradeNow: "Actualizar Ahora",
    unlockPremiumFeatures: "Desbloquear Funciones Premium",
    premiumUpsellDescription: "Accede a funciones premium con una suscripción",
    offlineActivities: "Actividades Sin Conexión",
    offlineActivitiesDesc: "Disfruta de actividades sin conexión a Internet",
    coloringBook: "Libro para Colorear",
    coloringBookDesc: "Un libro divertido para colorear",
    download: "Descargar",
    storyBook: "Libro de Cuentos",
    storyBookDesc: "Leer historias en cualquier momento",
    activityPack: "Paquete de Actividades",
    activityPackDesc: "Actividades adicionales para disfrutar",
    upgradeToDownload: "Actualizar para Descargar",
    familyAccountLinking: "Vinculación de Cuentas Familiares",
    familyAccountLinkingDesc: "Conecta varias cuentas familiares",
    premiumFeature: "Función Premium",
    familyLinkingPremiumDesc: "Vinculación familiar disponible en el plan premium",
    overview: "Resumen",
    progress: "Progreso",
    safety: "Seguridad",
    premium: "Premium",
    weeklyReport: "Informe Semanal (Aventuras)",
    noActivitiesYet: "Aún no hay actividades",
    achievements: "Logros",
    firstActivity: "Primera Actividad",
    completedFirstActivity: "Primera actividad completada",
    weekStreak: "Racha Semanal",
    sevenDaysInARow: "7 días seguidos",
    explorer: "Explorador",
    triedFiveActivities: "Probó 5 actividades diferentes",
    timeMaster: "Maestro del Tiempo",
    completedAllWeeklyActivities: "Completó todas las actividades semanales",
    viewAllAchievements: "Ver Todos los Logros",
    engagement: "Participación",
    activityReminders: "Recordatorios de Actividades",
    voiceAssistant: "Asistente de Voz",
    parentingTips: "Consejos de Crianza",
    sampleTip: "Consejo de Ejemplo",
    readMore: "Leer Más",
    screenTimeTrends: "Tendencias de Tiempo de Pantalla",
    activityCompletion: "Finalización de Actividad",
    completedPending: "Completado / Pendiente",
    comparisonView: "Vista Comparativa",
    compareProgress: "Comparar Progreso",
    bedtimeScheduler: "Programador de Hora de Dormir",
    bedtimeSchedulerDescription: "Configura la hora de dormir",
    startTime: "Hora de Inicio",
    endTime: "Hora de Fin",
    bedtimeActive: "Hora de Dormir Activa",
    bedtimeActiveDescription: "21:00 - 07:00",
    premiumUpsell: "Desbloquea funciones premium con suscripción",
    noSubscriptionTitle: "Aún sin suscripción",
    noSubscriptionDesc: "Suscríbete ahora para acceder a todas las funciones",
    unlockFeatures: "Desbloquear Funciones",

  },
  rw: {
    loading: "Irimo gupakurwa",
    parentZoneTitleSuffix: " - Akarere k'Ababyeyi",
    child: "Umwana",
    subtitleAgeRange: "Ku babyeyi b'abana bagerageza kumenya byinshi (imyaka 2–4)",
    addChild: "Ongeraho Umwana",
    addNewChild: "Ongeraho Umwana Mushya",
    childName: "Izina ry'Umwana",
    childNamePlaceholder: "Andika izina ry'umwana",
    saving: "Birimo kubikwa...",
    save: "Bika",
    cancel: "Kureka",
    saved: "Byahangiwe",
    profileSaved: "Umwirondoro wawe uvuguruwe",
    editProfile: "Hindura Umwirondoro",
    ageRange: "Igihe cy'imyaka",
    selectAge: "Hitamo imyaka",
    avatarUrl: "URL y'Ifoto",
    favoriteTheme: "Insanganyamatsiko Ukunda",
    selectTheme: "Hitamo insanganyamatsiko",
    themeOcean: "Inyanja",
    themeSpace: "Isanzure",
    themeSafari: "Safari",
    profileTip: "Inama: Vugurura umwirondoro kugirango ubone ibikorwa bikubereye.",
    weeklyAdventures: "Raporo y'Icyumweru (Ibikorwa)",
    thisWeek: "Iki cyumweru",
    day: "Umunsi",
    done: "byakozwe",
    missed: "ntibyakozwe",
    activitiesCompleted: "by'ibikorwa byakozwe!",
    settings: "Igenamiterere",
    screenTime: "Igihe kuri Ekrani",
    min: "imin",
    screenTimeHint: "Shyiraho igihe cya buri munsi giciriritse. Ushobora kugihindura igihe icyo ari cyo cyose.",
    bedtimeMode: "Uburyo bwo Kuryama",
    bedtimeHint: "Ihindura amabara akajya mu isura ituje nijoro.",
    kidSafeOnly: "Ibirimo by'Abana gusa",
    kidSafeHint: "Ishungura imyanya yo hanze. Koresha urutonde rwemewe.",
    whitelistTitle: "Imbuga zemerewe (hostname)",
    addDomain: "Ongeraho",
    remove: "Kuraho",
    addChildError: "Ikosa yoongerera umwana",
    upgradeRequired: "Kwirakwiza premium kwoongerera abana benshi",
    freePlanLimitReached:"Ugeze ku mipaka ya {max} abana ku gahunda y'ubuntu",
    domainPlaceholder: "ur. urugero.com",
    whitelistNote: "Bisanzwe, ibiri mu porogaramu gusa nibyo byemererwa.",
    blockedExternal: "Amahuzanya yo hanze yabujijwe n'uburyo bw'abana.",
    footerTagline: "Byakozwe n'❤️ ku rugendo rw'amasomo y'ibanze",
    premiumBenefits: "Ibyiza bya Premium",
    manageSubscription: "Tegeka Umunyamuryango",
    premiumPitch: "Ababyeyi bizeye Nimi ku mutekano n'isesengura ry'iterambere.",
    premiumBullet1: "Imikino n'inkuru 100+ byakozwe n'inzobere",
    premiumBullet2: "Isesengura ry'ubumenyi buri cyumweru rihuye n'umwana wawe",
    premiumBullet3: "Igenzura rihanitse ry'igihe kuri ekrani no kuryama",
    premiumBullet4: "Uburambe butekanye kandi nta matangazo",
    premiumBullet5: "Stika n'ibihembo bya Nimi Glory byihariye",
    premiumGuarantee: "Iminsi 14 y'igerageza. Ubwishyu bufite umutekano kandi bubika ibanga.",
    premiumDeliveriesTitle: "Ibyo twohereza buri cyumweru (Abanyamuryango)",
    weeklyHardStorybook: "Igitabo cy'inkuru gifite igikapu",
    weeklyColoringBook: "Igitabo cyo gushushanya",
    chooseDeliveryDay: "Hitamo umunsi wo koherezaho",
    subscribeToUnlockDeliveries: "Iyandikishe kugirango uhabwe ibitabo bya buri cyumweru.",
    savePreferences: "Bika ibyihariye",
    premiumTitle: "Premium",
    premiumHeadline: "Fungura urugendo rwo kwiga rufite ituze n'ubwenge",
    premiumSubhead: "Ibikoresho byemejwe n'ibisobanuro bishimishije ku myaka 2–4.",
    planMonthly: "Buri kwezi",
    planYearly: "Buri mwaka",
    bestValue: "Ihiga izindi",
    perMonth: "kuri kwezi",
    perYear: "kuri mwaka",
    f1: "Imikino n'inkuru za premium zidafite imipaka",
    f2: "Isesengura ry'iterambere buri cyumweru",
    f3: "Ibikoresho bihanitse by'igihe kuri ekrani",
    f4: "Uburambe budafite amatangazo kandi butekanye",
    f5: "Stika za Nimi Glory zidasanzwe",
    startTrial: "Tangira Igerageza",
    trialNote: "Uhagarika igihe icyo ari cyo cyose. Igerageza rihinduka ryahemberwa.",
    benefit1Title: "Giteza imbere",
    benefit1Desc: "Ibihembo nka Nimi Glory bitera imyitwarire myiza.",
    benefit2Title: "Byihariye",
    benefit2Desc: "Ibikorwa bihinduka bitewe n'uko umwana ameze.",
    benefit3Title: "Birinzwe",
    benefit3Desc: "Igenzura n'umutekano w'ibirimo byo ku rwego rwo hejuru.",
    backToParentZone: "Subira mu Karere k'Ababyeyi",
    downloadSticker: "Kuramo stika ya Nimi Glory",
    stickerPreviewTitle: "Stika ya Nimi Glory y'Icyumweru",
    stickerPreviewAlt: "Igaragaza stika ya Nimi Glory",
    parentProfileTitle: "Umwirondoro w'Umubyeyi",
    parentName: "Izina ryawe",
    parentEmail: "Imeli",
    notifyEmail: "Raporo za buri cyumweru kuri imeli",
    notifyEmailHint: "Akanyamakuru k'iterambere buri cyumweru.",
    marketingOptIn: "Amakuru & inama za porogaramu",
    marketingOptInHint: "Imeli nke zagufasha gukoresha Nimi neza.",
    authStatus: "Imiterere",
    authLogin: "Injira",
    authLogout: "Sohoka",
    loggedIn: "Winjiye",
    loggedOut: "Ntiwinjiye",
    loginError: "Kwinjira byanze",
    enterEmail: "Andika imeli yawe",
    subscriptionStatus: "Umunyamuryango",
    subscribed: "Yanditswe",
    notSubscribed: "Ntiyanditswe",
    remindersTitle: "Ibibutsa bya buri munsi byo kwiga",
    addReminder: "Ongeraho isaha",
    grantPermission: "Emeza amabwire",
    remindersHint: "Tuzibutsa umwana wawe ku masaha wahisemo.",
    notificationsEnabled: "Amabwire yemejwe",
    notificationsDenied: "Amabwire yabujijwe",
    learnReminderBody: "Igihe cyo kwiga na Nimi! Akanya gato gafasha cyane.",
    upgradeNow: "Hindura Ubu",
    unlockPremiumFeatures: "Fungura Ibikurikira bya Premium",
    premiumUpsellDescription: "Kwinjiza ibikurikira bya premium ukoresheje ubusabe",
    offlineActivities: "Ibikorwa Bidakeneye Internet",
    offlineActivitiesDesc: "Gira ibikorwa utarinze gukoresha internet",
    coloringBook: "Igitabo cyo Gushushanya",
    coloringBookDesc: "Igitabo cyiza cyo gushushanya",
    download: "Kuramo",
    storyBook: "Igitabo cy’Inkuru",
    storyBookDesc: "Soma inkuru igihe icyo ari cyo cyose",
    activityPack: "Agapaki k’Ibikorwa",
    activityPackDesc: "Ibikorwa byiyongera byo kwishimira",
    upgradeToDownload: "Hindura Kugira ngo Ukuramo",
    familyAccountLinking: "Guhuza Konti za Umuryango",
    familyAccountLinkingDesc: "Huzuzanya konti nyinshi z’umuryango",
    premiumFeature: "Ikiranga Premium",
    familyLinkingPremiumDesc: "Guhuza umuryango biboneka mu rwego rwa premium",
    overview: "Isuzuma",
    progress: "Iterambere",
    safety: "Umuryango",
    premium: "Premium",
    weeklyReport: "Raporo ya Icyumweru (Ibikorwa)",
    noActivitiesYet: "Nta bikorwa biriho",
    achievements: "Ibyagezweho",
    firstActivity: "Igikorwa cya Mbere",
    completedFirstActivity: "Wuzuye igikorwa cya mbere",
    weekStreak: "Urukurikirane rw'Icyumweru",
    sevenDaysInARow: "Iminsi 7 ikurikiranya",
    explorer: "Umushakashatsi",
    triedFiveActivities: "Wagerageje ibikorwa 5 bitandukanye",
    timeMaster: "Ushinzwe Igihe",
    completedAllWeeklyActivities: "Wuzuye ibikorwa byose by'icyumweru",
    viewAllAchievements: "Reba Ibyagezweho Byose",
    engagement: "Kwitabira",
    activityReminders: "Ibibutsa ibikorwa",
    voiceAssistant: "Ubufasha bw’Ijwi",
    parentingTips: "Inama z'Uburezi",
    sampleTip: "Inama y'Urugero",
    readMore: "Soma Ibindi",
    screenTimeTrends: "Imiterere y’Igihe cyo Ku Mudasobwa",
    activityCompletion: "Gusoza Igikorwa",
    completedPending: "Byarangiye / Biracyategereje",
    comparisonView: "Reba Ugereranye",
    compareProgress: "Gereranya Iterambere",
    bedtimeScheduler: "Igenamiterere ry'Isinzira",
    bedtimeSchedulerDescription: "Shyiraho igihe cyo kuryama",
    startTime: "Igihe cyo Gutangirira",
    endTime: "Igihe cyo Gusoza",
    bedtimeActive: "Igihe cyo Kuryama Cyatangiye",
    bedtimeActiveDescription: "21:00 - 07:00",
    premiumUpsell: "Fungura ibikurikira bya premium ukoresheje ubusabe",
    noSubscriptionTitle: "Nta Mwandiko w'Ubwishingizi",
    noSubscriptionDesc: "Iyandikishe ubu kugira ngo ubone ibikurikira byose",
    unlockFeatures: "Fungura Ibikurikira"

  },
}

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    if (typeof window === "undefined") return "en";
    return (localStorage.getItem(LANGUAGE_KEY) as Language) || "en";
  });

  useEffect(() => {
    const onStorage = (e: StorageEvent) => {
      if (e.key === LANGUAGE_KEY && e.newValue) {
        setLanguage(e.newValue as Language);
      }
    };
    
    window.addEventListener("storage", onStorage);
    
    const onCustom = (e: Event) => {
      const detail = (e as CustomEvent).detail as { language: Language };
      if (detail?.language) {
        localStorage.setItem(LANGUAGE_KEY, detail.language);
        setLanguage(detail.language);
      }
    };
    
    window.addEventListener("app:languageChange", onCustom as EventListener);
    
    return () => {
      window.removeEventListener("storage", onStorage);
      window.removeEventListener("app:languageChange", onCustom as EventListener);
    };
  }, []);

  const value = {
    language,
    setLanguage: (lang: Language) => {
      localStorage.setItem(LANGUAGE_KEY, lang);
      setLanguage(lang);
      window.dispatchEvent(
        new CustomEvent("app:languageChange", { detail: { language: lang } })
      );
    },
    t: (key: string) => {
      const table = dict[language] || dict.en;
      return table[key] ?? key;
    }
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}