-- ─────────────────────────────────────────────────────────────────────────────
-- Migration 135 — Nimi Intelligence V2
-- Adds: proactive_queue, conversation_summaries, supporting RPCs
-- ─────────────────────────────────────────────────────────────────────────────

-- ── proactive_queue ───────────────────────────────────────────────────────────
-- Stores pending proactive messages Nimi wants to deliver to a child.
-- Generated by the proactive engine, consumed by /api/nimi/proactive.
-- Delivered messages are soft-deleted (delivered_at set), never hard-deleted.

create table if not exists proactive_queue (
  id               uuid primary key default gen_random_uuid(),
  child_id         uuid not null references children(id) on delete cascade,
  suggestion_type  text not null check (suggestion_type in (
                     'achievement_congrats',
                     'story_followup',
                     'mission_recommend',
                     'vocab_review',
                     'certificate_nudge',
                     'community_invite',
                     'streak_celebrate',
                     'daily_checkin'
                   )),
  title            text not null,
  message          text not null,
  context_data     jsonb not null default '{}',
  priority         int  not null default 5,  -- 1 = highest, 10 = lowest
  expires_at       timestamptz not null default now() + interval '24 hours',
  delivered_at     timestamptz,
  created_at       timestamptz not null default now()
);

create index if not exists proactive_queue_child_pending_idx
  on proactive_queue (child_id, expires_at)
  where delivered_at is null;

-- RLS: owner can read, no direct writes (service-role only)
alter table proactive_queue enable row level security;
create policy proactive_queue_select on proactive_queue
  for select using (
    exists (
      select 1 from children c
      where c.id = proactive_queue.child_id
        and c.parent_id = auth.uid()
    )
  );

-- ── conversation_summaries ────────────────────────────────────────────────────
-- Persists AI-generated summaries of Nimi chat sessions.
-- Used to give Nimi memory across sessions without storing raw messages.

create table if not exists conversation_summaries (
  id             uuid primary key default gen_random_uuid(),
  child_id       uuid not null references children(id) on delete cascade,
  session_id     text not null,  -- client-generated (e.g. UUID or timestamp key)
  summary        text not null,  -- 2-4 sentence AI summary of what was discussed
  key_topics     text[] not null default '{}',
  mastered_vocab text[] not null default '{}',
  mistakes       jsonb  not null default '[]',  -- [{word, error_type, corrected_at}]
  language       text   not null default 'en',
  story_id       text,
  exchange_count int    not null default 0,
  created_at     timestamptz not null default now(),

  unique (child_id, session_id)
);

create index if not exists conversation_summaries_child_idx
  on conversation_summaries (child_id, created_at desc);

alter table conversation_summaries enable row level security;
create policy conversation_summaries_select on conversation_summaries
  for select using (
    exists (
      select 1 from children c
      where c.id = conversation_summaries.child_id
        and c.parent_id = auth.uid()
    )
  );

-- ── RPCs ──────────────────────────────────────────────────────────────────────

-- Fetch undelivered proactive suggestions for a child (ordered by priority).
create or replace function get_pending_proactive(
  p_child_id uuid,
  p_limit    int default 3
)
returns setof proactive_queue
language sql security definer set search_path = public as $$
  select *
  from proactive_queue
  where child_id = p_child_id
    and delivered_at is null
    and expires_at   > now()
  order by priority asc, created_at desc
  limit p_limit;
$$;

-- Mark proactive suggestions as delivered (by array of IDs).
create or replace function mark_proactive_delivered(
  p_ids uuid[]
)
returns void
language sql security definer set search_path = public as $$
  update proactive_queue
  set    delivered_at = now()
  where  id = any(p_ids);
$$;

-- Queue a proactive suggestion (idempotent: same child + type within 12h = skip).
create or replace function queue_proactive_suggestion(
  p_child_id       uuid,
  p_type           text,
  p_title          text,
  p_message        text,
  p_context_data   jsonb    default '{}',
  p_priority       int      default 5,
  p_expires_hours  int      default 24
)
returns uuid
language plpgsql security definer set search_path = public as $$
declare
  v_id uuid;
begin
  -- Deduplication: skip if same type already queued for this child in last 12h
  if exists (
    select 1 from proactive_queue
    where  child_id        = p_child_id
      and  suggestion_type = p_type
      and  delivered_at    is null
      and  created_at      > now() - interval '12 hours'
  ) then
    return null;
  end if;

  insert into proactive_queue
    (child_id, suggestion_type, title, message, context_data, priority, expires_at)
  values
    (p_child_id, p_type, p_title, p_message, p_context_data, p_priority,
     now() + (p_expires_hours || ' hours')::interval)
  returning id into v_id;

  return v_id;
end;
$$;

-- Upsert a conversation summary (creates or updates by session_id).
create or replace function upsert_conversation_summary(
  p_child_id       uuid,
  p_session_id     text,
  p_summary        text,
  p_key_topics     text[]   default '{}',
  p_mastered_vocab text[]   default '{}',
  p_mistakes       jsonb    default '[]',
  p_language       text     default 'en',
  p_story_id       text     default null,
  p_exchange_count int      default 0
)
returns void
language sql security definer set search_path = public as $$
  insert into conversation_summaries
    (child_id, session_id, summary, key_topics, mastered_vocab, mistakes, language, story_id, exchange_count)
  values
    (p_child_id, p_session_id, p_summary, p_key_topics, p_mastered_vocab, p_mistakes, p_language, p_story_id, p_exchange_count)
  on conflict (child_id, session_id) do update set
    summary        = excluded.summary,
    key_topics     = excluded.key_topics,
    mastered_vocab = excluded.mastered_vocab,
    mistakes       = excluded.mistakes,
    exchange_count = excluded.exchange_count;
$$;

-- Get recent conversation summaries for a child (for Nimi context injection).
create or replace function get_conversation_history(
  p_child_id uuid,
  p_limit    int default 5
)
returns table (
  session_id     text,
  summary        text,
  key_topics     text[],
  mastered_vocab text[],
  mistakes       jsonb,
  language       text,
  story_id       text,
  exchange_count int,
  created_at     timestamptz
)
language sql security definer set search_path = public as $$
  select session_id, summary, key_topics, mastered_vocab, mistakes,
         language, story_id, exchange_count, created_at
  from   conversation_summaries
  where  child_id = p_child_id
  order  by created_at desc
  limit  p_limit;
$$;
